// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg9NAcCG3N1zGTwSq5-6lG8bYjWLdH9mQ',
    appId: '1:1014340416116:web:c007b5ac709655adcb1721',
    messagingSenderId: '1014340416116',
    projectId: 'usershub',
    authDomain: 'usershub.firebaseapp.com',
    storageBucket: 'usershub.firebasestorage.app',
    measurementId: 'G-85DYT5N1C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fje-hhwUTZHPMlj1JcxuJSfjAwbPQcg',
    appId: '1:1014340416116:android:d9702ae088b38b56cb1721',
    messagingSenderId: '1014340416116',
    projectId: 'usershub',
    storageBucket: 'usershub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTTVtCJ6jsKUJsq24MCIbU_vjm_p_OVg8',
    appId: '1:1014340416116:ios:42152d1f42378004cb1721',
    messagingSenderId: '1014340416116',
    projectId: 'usershub',
    storageBucket: 'usershub.firebasestorage.app',
    iosBundleId: 'com.example.usersHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTTVtCJ6jsKUJsq24MCIbU_vjm_p_OVg8',
    appId: '1:1014340416116:ios:42152d1f42378004cb1721',
    messagingSenderId: '1014340416116',
    projectId: 'usershub',
    storageBucket: 'usershub.firebasestorage.app',
    iosBundleId: 'com.example.usersHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg9NAcCG3N1zGTwSq5-6lG8bYjWLdH9mQ',
    appId: '1:1014340416116:web:a33960027695a8adcb1721',
    messagingSenderId: '1014340416116',
    projectId: 'usershub',
    authDomain: 'usershub.firebaseapp.com',
    storageBucket: 'usershub.firebasestorage.app',
    measurementId: 'G-Q9P0T89M4J',
  );
}
